// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: ad/adviertisement.proto

package ad

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AdviertisementService service

func NewAdviertisementServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AdviertisementService service

type AdviertisementService interface {
	QueryAdviertisement(ctx context.Context, in *QueryByExampleRequest, opts ...client.CallOption) (*QueryByExampleResponse, error)
}

type adviertisementService struct {
	c    client.Client
	name string
}

func NewAdviertisementService(name string, c client.Client) AdviertisementService {
	return &adviertisementService{
		c:    c,
		name: name,
	}
}

func (c *adviertisementService) QueryAdviertisement(ctx context.Context, in *QueryByExampleRequest, opts ...client.CallOption) (*QueryByExampleResponse, error) {
	req := c.c.NewRequest(c.name, "AdviertisementService.QueryAdviertisement", in)
	out := new(QueryByExampleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdviertisementService service

type AdviertisementServiceHandler interface {
	QueryAdviertisement(context.Context, *QueryByExampleRequest, *QueryByExampleResponse) error
}

func RegisterAdviertisementServiceHandler(s server.Server, hdlr AdviertisementServiceHandler, opts ...server.HandlerOption) error {
	type adviertisementService interface {
		QueryAdviertisement(ctx context.Context, in *QueryByExampleRequest, out *QueryByExampleResponse) error
	}
	type AdviertisementService struct {
		adviertisementService
	}
	h := &adviertisementServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AdviertisementService{h}, opts...))
}

type adviertisementServiceHandler struct {
	AdviertisementServiceHandler
}

func (h *adviertisementServiceHandler) QueryAdviertisement(ctx context.Context, in *QueryByExampleRequest, out *QueryByExampleResponse) error {
	return h.AdviertisementServiceHandler.QueryAdviertisement(ctx, in, out)
}
